version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:9'
    working_directory: ~/portfilio
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}'
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}'
      - run: yarn test
