backend:
  name: git-gateway
  branch: master
slug:
  encoding: ascii
  clean_accents: true
display_url: 'https://kamontat.space'
media_folder: static/uploads/images
public_folder: /uploads/images
collections:
  - label: Information
    name: informations
    files:
      - label: Personal information
        name: profile
        file: src/_personal/personal.yaml
        editor:
          preview: false
        fields:
          - label: Abbreviation
            name: abbreviation
            widget: string
          - label: Profile Image
            name: image
            widget: image
          - label: Name
            name: name
            widget: object
            fields:
              - label: First name
                name: first-name
                widget: string
              - label: Last name
                name: last-name
                widget: string
          - label: Email
            name: email
            widget: string
          - label: Birthday
            name: birthday
            widget: date
            format: DD-MMM-YYYY
          - label: Address
            name: address
            widget: text
          - label: Phone number
            name: phone
            widget: string
  - label: Education
    name: education
    folder: src/_personal/education
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}-{{position}}'
    fields:
      - label: School Name
        name: title
        widget: string
      - label: Course Name
        name: course
        widget: string
      - label: Start date
        name: start
        widget: date
        format: DD-MMM-YYYY
      - label: End Date
        name: end
        widget: date
        format: DD-MMM-YYYY
      - label: Position
        name: position
        widget: number
        valueType: int
        required: false
        default: 0
