backend:
  name: git-gateway
  branch: dev
  commit_messages:
    create: '[cms] Create {{collection}} {{slug}}'
    update: '[cms] Update {{collection}} {{slug}}'
    delete: '[cms] Delete {{collection}} {{slug}}'
    uploadMedia: '[cms] Upload {{path}}'
    deleteMedia: '[cms] Delete {{path}}'
slug:
  encoding: ascii
  clean_accents: true
display_url: 'https://kamontat.space'
media_folder: static/uploads/images
public_folder: /uploads/images
collections:
  - label: Personal
    name: personal
    files:
      - label: Information
        name: information
        file: src/_personal/personal.yml
        editor:
          preview: false
        fields:
          - label: Abbreviation
            name: abbreviation
            widget: string
            pattern:
              - '[a-zA-Z]{1,3}'
              - Abbreviation shouldn't longer that 3 charector
          - label: Profile Image
            name: image
            widget: image
          - label: Name
            name: name
            widget: object
            fields:
              - label: First name
                name: first_name
                widget: string
              - label: Last name
                name: last_name
                widget: string
          - label: Nickname
            name: nickname
            widget: string
            required: false
          - label: Email
            name: email
            widget: string
            pattern:
              - >-
                (([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))
              - Email must include name@domain.protocol
          - label: Birthday
            name: birthday
            widget: date
            format: DD-MMM-YYYY
            required: false
          - label: Address
            name: address
            widget: text
            required: false
          - label: Phone number
            name: phone
            widget: string
            pattern:
              - '+[0-9]\d*'
              - Phone number must be format +XXX00000000
      - label: Extra Information
        name: extra_information
        file: src/_personal/extra-information.yml
        editor:
          preview: false
        fields:
          - label: Expected Job Position
            name: expected_position
            widget: string
            required: false
          - label: Current Job Position
            name: current_position
            widget: string
            required: false
          - label: Industry
            name: industry
            widget: string
            required: false
          - label: Quote
            name: quote
            widget: text
            required: false
          - label: Resume File
            name: resume
            widget: file
            default: /uploads/images/kamontat-resume.pdf
            required: false
          - label: CV File
            name: cv
            widget: file
            default: /uploads/images/kamontat-cv.pdf
            required: false
      - label: Social Media
        name: social
        file: src/_personal/social.yml
        editor:
          preview: false
        fields:
          - label: Facebook username
            name: facebook
            widget: string
            hint: this should contains username only
            required: false
          - label: Twitter username
            name: twitter
            widget: string
            hint: this should contains username only
            required: false
          - label: Linkedin username
            name: linkedin
            widget: string
            hint: this should contains username only
            required: false
          - label: Line ID
            name: line
            widget: string
            hint: this should contains line id only
            required: false
          - label: Medium username
            name: medium
            widget: string
            hint: this should contains username only
            required: false
          - label: Github username
            name: github
            widget: string
            hint: this should contains username only
            required: false
          - label: Storylog username
            name: storylog
            widget: string
            hint: this should contains username only
            required: false
          - label: Website url
            name: website
            widget: string
            pattern:
              - >-
                https?:\/\/(www\\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)
              - This must be fully url link
            hint: 'this should contains fully url (include http:// or https://)'
            required: false
  - label: Educations
    name: educations
    folder: src/_personal/educations
    create: true
    extension: yml
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: School Name
        name: title
        widget: string
      - label: Short School Name
        name: short
        widget: string
      - label: Course Name
        name: course
        widget: string
      - label: GPAX
        name: gpax
        widget: object
        hint: 'if select gpax as pass or fail, you didn''t need to add score textfield'
        fields:
          - label: Type
            name: type
            widget: select
            options:
              - label: Scoring
                value: scoring
              - label: Pass or Fail
                value: PF
          - label: Score
            name: score
            widget: number
            valueType: float
            min: 0
            max: 4
            required: false
      - label: Date
        name: date
        widget: object
        fields:
          - label: Start
            name: start
            widget: date
            format: DD-MMM-YYYY
          - label: End
            name: end
            widget: date
            format: DD-MMM-YYYY
            required: false
      - label: Certificates
        name: certificates
        widget: list
        field:
          label: Certificate
          name: certificate
          widget: file
        required: false
      - label: Position
        name: position
        widget: number
        valueType: int
        required: false
        pattern:
          - (\s*|\d+)
          - This must be position interger or empty value only
        default: 0
  - label: Experiences
    name: experiences
    folder: src/_personal/experiences
    create: true
    extension: yml
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}'
    fields:
      - label: Type
        name: type
        widget: select
        options:
          - label: Work
            value: work
          - label: Internship
            value: internship
          - label: Part-time
            value: parttime
          - label: Competition
            value: competition
      - label: Images
        name: images
        widget: list
        field:
          label: Image
          name: image
          widget: image
        required: false
      - label: Title
        name: title
        widget: string
      - label: Location
        name: location
        widget: string
      - label: Location Link
        name: location_link
        widget: string
        required: false
        pattern:
          - >-
            https?:\/\/(www\\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)
          - This must be fully url link
      - label: Description
        name: description
        widget: text
        required: false
      - label: Accomplishes
        name: accomplishes
        widget: list
        required: false
        field:
          label: On
          name: on
          widget: string
      - label: Certificates
        name: certificates
        widget: list
        field:
          label: Certificate
          name: certificate
          widget: file
        required: false
      - label: Date
        name: date
        widget: object
        fields:
          - label: Start
            name: start
            widget: date
            format: DD-MMM-YYYY
            required: false
          - label: End
            name: end
            widget: date
            format: DD-MMM-YYYY
            required: false
      - label: Position
        name: position
        widget: number
        valueType: int
        required: false
        pattern:
          - (\s*|\d+)
          - This must be position interger or empty value only
        default: 0
  - label: Projects
    name: projects
    folder: src/_personal/projects
    create: true
    extension: yml
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Image
        name: image
        widget: image
      - label: Name
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Date
        name: date
        widget: object
        fields:
          - label: Start
            name: start
            widget: date
            format: DD-MMM-YYYY
            required: false
          - label: End
            name: end
            widget: date
            format: DD-MMM-YYYY
            required: false
      - label: Project link
        name: link
        widget: string
        required: false
        pattern:
          - >-
            https?:\/\/(www\\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)
          - This must be fully url link
        hint: 'this should contains fully url (include http:// or https://)'
      - label: Position
        name: position
        widget: number
        valueType: int
        required: false
        pattern:
          - (\s*|\d+)
          - This must be position interger or empty value only
        default: 0
  - label: Languages
    name: languages
    folder: src/_personal/languages
    create: true
    extension: yml
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Name
        name: name
        widget: relation
        hint: 'this textfield have selection list, but it might slow. calm down'
        collection: locates
        searchFields:
          - title
          - code
        valueField: title
        displayFields:
          - title
      - label: Name@1
        name: title
        widget: string
        hint: 'cause by netlify convension, copy name and paste here'
      - label: Level
        name: level
        widget: select
        options:
          - label: Elementary proficiency
            value: 1
          - label: Limited working proficiency
            value: 2
          - label: Professional working proficiency
            value: 3
          - label: Full professional proficiency
            value: 4
          - label: Native or bilingual proficiency
            value: 5
      - label: Position
        name: position
        widget: number
        valueType: int
        required: false
        pattern:
          - (\s*|\d+)
          - This must be position interger or empty value only
        default: 0
  - label: Skills
    name: skills
    folder: src/_personal/skills
    create: true
    extension: yml
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Type
        name: type
        widget: select
        options:
          - label: Knowledge based
            value: knowledge
          - label: Personal Attitudes
            value: attitude
          - label: Functional
            value: functional
      - label: Tags
        name: tags
        widget: list
        field:
          label: Tag
          name: tag
          widget: string
      - label: Name
        name: title
        widget: string
      - label: Level
        name: level
        widget: select
        options:
          - label: Elementary proficiency
            value: 1
          - label: Limited working proficiency
            value: 2
          - label: Professional working proficiency
            value: 3
          - label: Full professional proficiency
            value: 4
      - label: Position
        name: position
        widget: number
        valueType: int
        required: false
        pattern:
          - (\s*|\d+)
          - This must be position interger or empty value only
        default: 0
  - label: Locates
    name: locates
    folder: src/_personal/locates
    create: true
    extension: yml
    editor:
      preview: false
    slug: '{{slug}}'
    fields:
      - label: Code
        name: code
        widget: string
      - label: Name
        name: title
        widget: string
