backend:
  name: git-gateway
  branch: master
media_folder: static/uploads/images
public_folder: /uploads/images
collections:
  - name: education
    label: Education
    folder: src/_personal/education
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{position}}'
    fields:
      - label: School Name
        name: title
        widget: string
      - label: Course Name
        name: course
        widget: string
      - label: Start date
        name: start
        widget: date
        format: DD-MMM-YYYY
      - label: End Date
        name: end
        widget: date
        format: DD-MMM-YYYY
      - label: Position
        name: position
        widget: number
        valueType: int
        required: false
        default: 0
